"""initial_schema_v3

Revision ID: f4318b2b2f9a
Revises: 
Create Date: 2026-02-26 20:15:10.663577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4318b2b2f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_disasters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('record_id_original', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('codigo_municipio', sa.String(length=7), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tipo_desastre', sa.String(length=50), nullable=False),
    sa.Column('subtipo_desastre', sa.String(length=100), nullable=True),
    sa.Column('intensidade', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('mortes_diretas', sa.Integer(), nullable=True),
    sa.Column('mortes_indiretas', sa.Integer(), nullable=True),
    sa.Column('feridos', sa.Integer(), nullable=True),
    sa.Column('desabrigados', sa.Integer(), nullable=True),
    sa.Column('desalojados', sa.Integer(), nullable=True),
    sa.Column('afetados', sa.Integer(), nullable=True),
    sa.Column('prejuizo_estimado', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_disasters'))
    )
    with op.batch_alter_table('atlas_disasters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atlas_disasters_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_codigo_municipio'), ['codigo_municipio'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_intensidade'), ['intensidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_municipio'), ['municipio'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_record_id_original'), ['record_id_original'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_tipo_desastre'), ['tipo_desastre'], unique=False)
        batch_op.create_index(batch_op.f('ix_atlas_disasters_uf'), ['uf'], unique=False)

    op.create_table('atlas_municipios_geocode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_municipio_ibge', sa.String(length=7), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('populacao', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('regiao', sa.String(length=20), nullable=True),
    sa.Column('mesorregiao', sa.String(length=100), nullable=True),
    sa.Column('microrregiao', sa.String(length=100), nullable=True),
    sa.Column('fonte_geocodigo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_municipios_geocode'))
    )
    with op.batch_alter_table('atlas_municipios_geocode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atlas_municipios_geocode_codigo_municipio_ibge'), ['codigo_municipio_ibge'], unique=True)
        batch_op.create_index(batch_op.f('ix_atlas_municipios_geocode_uf'), ['uf'], unique=False)

    op.create_table('blockchain_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('token_uid', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('explorer_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_transactions'))
    )
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_token_uid'), ['token_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_tx_hash'), ['tx_hash'], unique=True)

    op.create_table('oracle_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('disaster_type', sa.String(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('payout_triggered', sa.Boolean(), nullable=True),
    sa.Column('payout_percentage', sa.Float(), nullable=True),
    sa.Column('payout_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('blockchain_tx_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oracle_events'))
    )
    with op.batch_alter_table('oracle_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oracle_events_blockchain_tx_id'), ['blockchain_tx_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oracle_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_oracle_events_token_id'), ['token_id'], unique=False)

    op.create_table('partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_slug'), ['slug'], unique=True)

    op.create_table('space_weather_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('kp_index', sa.Float(), nullable=True),
    sa.Column('ap_index', sa.Float(), nullable=True),
    sa.Column('solar_flux', sa.Float(), nullable=True),
    sa.Column('geomagnetic_storm', sa.Boolean(), nullable=True),
    sa.Column('storm_level', sa.String(), nullable=True),
    sa.Column('solar_radiation_storm', sa.Boolean(), nullable=True),
    sa.Column('radiation_level', sa.String(), nullable=True),
    sa.Column('radio_blackout', sa.Boolean(), nullable=True),
    sa.Column('blackout_level', sa.String(), nullable=True),
    sa.Column('conjunction_risk_level', sa.String(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_weather_logs'))
    )
    with op.batch_alter_table('space_weather_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_weather_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_api_keys_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_locations_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_users_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('climate_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('temperature_avg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('temperature_max', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('precipitation', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_climate_data_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_climate_data'))
    )
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('coverage_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('premium', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('payout_structure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_policies_location_id_locations')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_policies_partner_id_partners')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('policy_number', name=op.f('uq_policies_policy_number'))
    )
    op.create_table('claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('claimed_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('approved_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('weather_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_claims_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('claim_number', name=op.f('uq_claims_claim_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    op.drop_table('policies')
    op.drop_table('climate_data')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('api_keys')
    with op.batch_alter_table('space_weather_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_weather_logs_timestamp'))

    op.drop_table('space_weather_logs')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_slug'))

    op.drop_table('partners')
    with op.batch_alter_table('oracle_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oracle_events_token_id'))
        batch_op.drop_index(batch_op.f('ix_oracle_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_oracle_events_blockchain_tx_id'))

    op.drop_table('oracle_events')
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_token_uid'))

    op.drop_table('blockchain_transactions')
    with op.batch_alter_table('atlas_municipios_geocode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atlas_municipios_geocode_uf'))
        batch_op.drop_index(batch_op.f('ix_atlas_municipios_geocode_codigo_municipio_ibge'))

    op.drop_table('atlas_municipios_geocode')
    with op.batch_alter_table('atlas_disasters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_uf'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_tipo_desastre'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_record_id_original'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_municipio'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_intensidade'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_created_at'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_codigo_municipio'))
        batch_op.drop_index(batch_op.f('ix_atlas_disasters_ano'))

    op.drop_table('atlas_disasters')
    # ### end Alembic commands ###
